spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviedb?characterEncoding=UTF-8
    username: root
    password: password
    initial-size: 1
    max-idle: 3
    min-idle: 1

server:
  port: 8081
  servlet:
    context-path: /

#mybatis:
#  mapper-locations: classpath:com/example/todo/repository/mybatis/*.xml
#  mapper-
